(cl:defpackage grounding_sam_ros-srv
  (:use )
  (:export
   "UPDATEPROMPT"
   "<UPDATEPROMPT-REQUEST>"
   "UPDATEPROMPT-REQUEST"
   "<UPDATEPROMPT-RESPONSE>"
   "UPDATEPROMPT-RESPONSE"
   "VITDETECTION"
   "<VITDETECTION-REQUEST>"
   "VITDETECTION-REQUEST"
   "<VITDETECTION-RESPONSE>"
   "VITDETECTION-RESPONSE"
  ))

