// Generated by gencpp from file grounding_sam_ros/UpdatePromptRequest.msg
// DO NOT EDIT!


#ifndef GROUNDING_SAM_ROS_MESSAGE_UPDATEPROMPTREQUEST_H
#define GROUNDING_SAM_ROS_MESSAGE_UPDATEPROMPTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grounding_sam_ros
{
template <class ContainerAllocator>
struct UpdatePromptRequest_
{
  typedef UpdatePromptRequest_<ContainerAllocator> Type;

  UpdatePromptRequest_()
    : data()  {
    }
  UpdatePromptRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdatePromptRequest_

typedef ::grounding_sam_ros::UpdatePromptRequest_<std::allocator<void> > UpdatePromptRequest;

typedef boost::shared_ptr< ::grounding_sam_ros::UpdatePromptRequest > UpdatePromptRequestPtr;
typedef boost::shared_ptr< ::grounding_sam_ros::UpdatePromptRequest const> UpdatePromptRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator1> & lhs, const ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator1> & lhs, const ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grounding_sam_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992ce8a1687cec8cULL;
  static const uint64_t static_value2 = 0x8bd883ec73ca41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grounding_sam_ros/UpdatePromptRequest";
  }

  static const char* value(const ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request params\n"
"string data\n"
;
  }

  static const char* value(const ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdatePromptRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grounding_sam_ros::UpdatePromptRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUNDING_SAM_ROS_MESSAGE_UPDATEPROMPTREQUEST_H
