// Generated by gencpp from file grounding_sam_ros/UpdatePrompt.msg
// DO NOT EDIT!


#ifndef GROUNDING_SAM_ROS_MESSAGE_UPDATEPROMPT_H
#define GROUNDING_SAM_ROS_MESSAGE_UPDATEPROMPT_H

#include <ros/service_traits.h>


#include <grounding_sam_ros/UpdatePromptRequest.h>
#include <grounding_sam_ros/UpdatePromptResponse.h>


namespace grounding_sam_ros
{

struct UpdatePrompt
{

typedef UpdatePromptRequest Request;
typedef UpdatePromptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdatePrompt
} // namespace grounding_sam_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grounding_sam_ros::UpdatePrompt > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::grounding_sam_ros::UpdatePrompt&) { return value(); }
};

template<>
struct DataType< ::grounding_sam_ros::UpdatePrompt > {
  static const char* value()
  {
    return "grounding_sam_ros/UpdatePrompt";
  }

  static const char* value(const ::grounding_sam_ros::UpdatePrompt&) { return value(); }
};


// service_traits::MD5Sum< ::grounding_sam_ros::UpdatePromptRequest> should match
// service_traits::MD5Sum< ::grounding_sam_ros::UpdatePrompt >
template<>
struct MD5Sum< ::grounding_sam_ros::UpdatePromptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grounding_sam_ros::UpdatePrompt >::value();
  }
  static const char* value(const ::grounding_sam_ros::UpdatePromptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grounding_sam_ros::UpdatePromptRequest> should match
// service_traits::DataType< ::grounding_sam_ros::UpdatePrompt >
template<>
struct DataType< ::grounding_sam_ros::UpdatePromptRequest>
{
  static const char* value()
  {
    return DataType< ::grounding_sam_ros::UpdatePrompt >::value();
  }
  static const char* value(const ::grounding_sam_ros::UpdatePromptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grounding_sam_ros::UpdatePromptResponse> should match
// service_traits::MD5Sum< ::grounding_sam_ros::UpdatePrompt >
template<>
struct MD5Sum< ::grounding_sam_ros::UpdatePromptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grounding_sam_ros::UpdatePrompt >::value();
  }
  static const char* value(const ::grounding_sam_ros::UpdatePromptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grounding_sam_ros::UpdatePromptResponse> should match
// service_traits::DataType< ::grounding_sam_ros::UpdatePrompt >
template<>
struct DataType< ::grounding_sam_ros::UpdatePromptResponse>
{
  static const char* value()
  {
    return DataType< ::grounding_sam_ros::UpdatePrompt >::value();
  }
  static const char* value(const ::grounding_sam_ros::UpdatePromptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUNDING_SAM_ROS_MESSAGE_UPDATEPROMPT_H
