// Generated by gencpp from file grounding_sam_ros/VitDetectionRequest.msg
// DO NOT EDIT!


#ifndef GROUNDING_SAM_ROS_MESSAGE_VITDETECTIONREQUEST_H
#define GROUNDING_SAM_ROS_MESSAGE_VITDETECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace grounding_sam_ros
{
template <class ContainerAllocator>
struct VitDetectionRequest_
{
  typedef VitDetectionRequest_<ContainerAllocator> Type;

  VitDetectionRequest_()
    : color_image()
    , prompt()  {
    }
  VitDetectionRequest_(const ContainerAllocator& _alloc)
    : color_image(_alloc)
    , prompt(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _color_image_type;
  _color_image_type color_image;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _prompt_type;
  _prompt_type prompt;





  typedef boost::shared_ptr< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VitDetectionRequest_

typedef ::grounding_sam_ros::VitDetectionRequest_<std::allocator<void> > VitDetectionRequest;

typedef boost::shared_ptr< ::grounding_sam_ros::VitDetectionRequest > VitDetectionRequestPtr;
typedef boost::shared_ptr< ::grounding_sam_ros::VitDetectionRequest const> VitDetectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator1> & lhs, const ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.color_image == rhs.color_image &&
    lhs.prompt == rhs.prompt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator1> & lhs, const ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grounding_sam_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4f89486a1428e7fd375da4293bd8185";
  }

  static const char* value(const ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4f89486a1428e7fULL;
  static const uint64_t static_value2 = 0xd375da4293bd8185ULL;
};

template<class ContainerAllocator>
struct DataType< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grounding_sam_ros/VitDetectionRequest";
  }

  static const char* value(const ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request params\n"
"sensor_msgs/Image color_image\n"
"string prompt\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color_image);
      stream.next(m.prompt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VitDetectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grounding_sam_ros::VitDetectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "color_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.color_image);
    s << indent << "prompt: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.prompt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUNDING_SAM_ROS_MESSAGE_VITDETECTIONREQUEST_H
