// Generated by gencpp from file grounding_sam_ros/VitDetection.msg
// DO NOT EDIT!


#ifndef GROUNDING_SAM_ROS_MESSAGE_VITDETECTION_H
#define GROUNDING_SAM_ROS_MESSAGE_VITDETECTION_H

#include <ros/service_traits.h>


#include <grounding_sam_ros/VitDetectionRequest.h>
#include <grounding_sam_ros/VitDetectionResponse.h>


namespace grounding_sam_ros
{

struct VitDetection
{

typedef VitDetectionRequest Request;
typedef VitDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VitDetection
} // namespace grounding_sam_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grounding_sam_ros::VitDetection > {
  static const char* value()
  {
    return "66a90572757b1f3f2629d2e4bea82842";
  }

  static const char* value(const ::grounding_sam_ros::VitDetection&) { return value(); }
};

template<>
struct DataType< ::grounding_sam_ros::VitDetection > {
  static const char* value()
  {
    return "grounding_sam_ros/VitDetection";
  }

  static const char* value(const ::grounding_sam_ros::VitDetection&) { return value(); }
};


// service_traits::MD5Sum< ::grounding_sam_ros::VitDetectionRequest> should match
// service_traits::MD5Sum< ::grounding_sam_ros::VitDetection >
template<>
struct MD5Sum< ::grounding_sam_ros::VitDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grounding_sam_ros::VitDetection >::value();
  }
  static const char* value(const ::grounding_sam_ros::VitDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grounding_sam_ros::VitDetectionRequest> should match
// service_traits::DataType< ::grounding_sam_ros::VitDetection >
template<>
struct DataType< ::grounding_sam_ros::VitDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::grounding_sam_ros::VitDetection >::value();
  }
  static const char* value(const ::grounding_sam_ros::VitDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grounding_sam_ros::VitDetectionResponse> should match
// service_traits::MD5Sum< ::grounding_sam_ros::VitDetection >
template<>
struct MD5Sum< ::grounding_sam_ros::VitDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grounding_sam_ros::VitDetection >::value();
  }
  static const char* value(const ::grounding_sam_ros::VitDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grounding_sam_ros::VitDetectionResponse> should match
// service_traits::DataType< ::grounding_sam_ros::VitDetection >
template<>
struct DataType< ::grounding_sam_ros::VitDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::grounding_sam_ros::VitDetection >::value();
  }
  static const char* value(const ::grounding_sam_ros::VitDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUNDING_SAM_ROS_MESSAGE_VITDETECTION_H
