// Generated by gencpp from file grounding_sam_ros/VitDetectionResponse.msg
// DO NOT EDIT!


#ifndef GROUNDING_SAM_ROS_MESSAGE_VITDETECTIONRESPONSE_H
#define GROUNDING_SAM_ROS_MESSAGE_VITDETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>
#include <sensor_msgs/Image.h>
#include <std_msgs/Float32MultiArray.h>

namespace grounding_sam_ros
{
template <class ContainerAllocator>
struct VitDetectionResponse_
{
  typedef VitDetectionResponse_<ContainerAllocator> Type;

  VitDetectionResponse_()
    : labels()
    , class_id()
    , boxes()
    , scores()
    , annotated_frame()
    , segmasks()  {
    }
  VitDetectionResponse_(const ContainerAllocator& _alloc)
    : labels(_alloc)
    , class_id(_alloc)
    , boxes(_alloc)
    , scores(_alloc)
    , annotated_frame(_alloc)
    , segmasks(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _labels_type;
  _labels_type labels;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _class_id_type;
  _class_id_type class_id;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _boxes_type;
  _boxes_type boxes;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _scores_type;
  _scores_type scores;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _annotated_frame_type;
  _annotated_frame_type annotated_frame;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _segmasks_type;
  _segmasks_type segmasks;





  typedef boost::shared_ptr< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VitDetectionResponse_

typedef ::grounding_sam_ros::VitDetectionResponse_<std::allocator<void> > VitDetectionResponse;

typedef boost::shared_ptr< ::grounding_sam_ros::VitDetectionResponse > VitDetectionResponsePtr;
typedef boost::shared_ptr< ::grounding_sam_ros::VitDetectionResponse const> VitDetectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator1> & lhs, const ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.labels == rhs.labels &&
    lhs.class_id == rhs.class_id &&
    lhs.boxes == rhs.boxes &&
    lhs.scores == rhs.scores &&
    lhs.annotated_frame == rhs.annotated_frame &&
    lhs.segmasks == rhs.segmasks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator1> & lhs, const ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grounding_sam_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc9fa720d67167700993761350e404df";
  }

  static const char* value(const ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc9fa720d6716770ULL;
  static const uint64_t static_value2 = 0x0993761350e404dfULL;
};

template<class ContainerAllocator>
struct DataType< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grounding_sam_ros/VitDetectionResponse";
  }

  static const char* value(const ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response params\n"
"string[] labels\n"
"int32[] class_id\n"
"std_msgs/Float32MultiArray boxes\n"
"float32[] scores\n"
"sensor_msgs/Image annotated_frame\n"
"std_msgs/Float32MultiArray segmasks\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.labels);
      stream.next(m.class_id);
      stream.next(m.boxes);
      stream.next(m.scores);
      stream.next(m.annotated_frame);
      stream.next(m.segmasks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VitDetectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grounding_sam_ros::VitDetectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "labels[]" << std::endl;
    for (size_t i = 0; i < v.labels.size(); ++i)
    {
      s << indent << "  labels[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.labels[i]);
    }
    s << indent << "class_id[]" << std::endl;
    for (size_t i = 0; i < v.class_id.size(); ++i)
    {
      s << indent << "  class_id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.class_id[i]);
    }
    s << indent << "boxes: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.boxes);
    s << indent << "scores[]" << std::endl;
    for (size_t i = 0; i < v.scores.size(); ++i)
    {
      s << indent << "  scores[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.scores[i]);
    }
    s << indent << "annotated_frame: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.annotated_frame);
    s << indent << "segmasks: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.segmasks);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUNDING_SAM_ROS_MESSAGE_VITDETECTIONRESPONSE_H
