// Generated by gencpp from file arx_r5_msg/RobotStatus.msg
// DO NOT EDIT!


#ifndef ARX_R5_MSG_MESSAGE_ROBOTSTATUS_H
#define ARX_R5_MSG_MESSAGE_ROBOTSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace arx_r5_msg
{
template <class ContainerAllocator>
struct RobotStatus_
{
  typedef RobotStatus_<ContainerAllocator> Type;

  RobotStatus_()
    : header()
    , end_pos()
    , joint_pos()
    , joint_vel()
    , joint_cur()  {
      end_pos.assign(0.0);

      joint_pos.assign(0.0);

      joint_vel.assign(0.0);

      joint_cur.assign(0.0);
  }
  RobotStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , end_pos()
    , joint_pos()
    , joint_vel()
    , joint_cur()  {
  (void)_alloc;
      end_pos.assign(0.0);

      joint_pos.assign(0.0);

      joint_vel.assign(0.0);

      joint_cur.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 6>  _end_pos_type;
  _end_pos_type end_pos;

   typedef boost::array<double, 7>  _joint_pos_type;
  _joint_pos_type joint_pos;

   typedef boost::array<double, 7>  _joint_vel_type;
  _joint_vel_type joint_vel;

   typedef boost::array<double, 7>  _joint_cur_type;
  _joint_cur_type joint_cur;





  typedef boost::shared_ptr< ::arx_r5_msg::RobotStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arx_r5_msg::RobotStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatus_

typedef ::arx_r5_msg::RobotStatus_<std::allocator<void> > RobotStatus;

typedef boost::shared_ptr< ::arx_r5_msg::RobotStatus > RobotStatusPtr;
typedef boost::shared_ptr< ::arx_r5_msg::RobotStatus const> RobotStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arx_r5_msg::RobotStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arx_r5_msg::RobotStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arx_r5_msg::RobotStatus_<ContainerAllocator1> & lhs, const ::arx_r5_msg::RobotStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.end_pos == rhs.end_pos &&
    lhs.joint_pos == rhs.joint_pos &&
    lhs.joint_vel == rhs.joint_vel &&
    lhs.joint_cur == rhs.joint_cur;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arx_r5_msg::RobotStatus_<ContainerAllocator1> & lhs, const ::arx_r5_msg::RobotStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arx_r5_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arx_r5_msg::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arx_r5_msg::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arx_r5_msg::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arx_r5_msg::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arx_r5_msg::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arx_r5_msg::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arx_r5_msg::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ad8a32d4f4533dc88ed7ddb658fce71";
  }

  static const char* value(const ::arx_r5_msg::RobotStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ad8a32d4f4533dcULL;
  static const uint64_t static_value2 = 0x88ed7ddb658fce71ULL;
};

template<class ContainerAllocator>
struct DataType< ::arx_r5_msg::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arx_r5_msg/RobotStatus";
  }

  static const char* value(const ::arx_r5_msg::RobotStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arx_r5_msg::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64[6] end_pos\n"
"\n"
"float64[7] joint_pos\n"
"float64[7] joint_vel\n"
"float64[7] joint_cur\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::arx_r5_msg::RobotStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arx_r5_msg::RobotStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.end_pos);
      stream.next(m.joint_pos);
      stream.next(m.joint_vel);
      stream.next(m.joint_cur);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arx_r5_msg::RobotStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arx_r5_msg::RobotStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "end_pos[]" << std::endl;
    for (size_t i = 0; i < v.end_pos.size(); ++i)
    {
      s << indent << "  end_pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.end_pos[i]);
    }
    s << indent << "joint_pos[]" << std::endl;
    for (size_t i = 0; i < v.joint_pos.size(); ++i)
    {
      s << indent << "  joint_pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_pos[i]);
    }
    s << indent << "joint_vel[]" << std::endl;
    for (size_t i = 0; i < v.joint_vel.size(); ++i)
    {
      s << indent << "  joint_vel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_vel[i]);
    }
    s << indent << "joint_cur[]" << std::endl;
    for (size_t i = 0; i < v.joint_cur.size(); ++i)
    {
      s << indent << "  joint_cur[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_cur[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARX_R5_MSG_MESSAGE_ROBOTSTATUS_H
