// Generated by gencpp from file arx_msgs/PosCmd.msg
// DO NOT EDIT!


#ifndef ARX_MSGS_MESSAGE_POSCMD_H
#define ARX_MSGS_MESSAGE_POSCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arx_msgs
{
template <class ContainerAllocator>
struct PosCmd_
{
  typedef PosCmd_<ContainerAllocator> Type;

  PosCmd_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , gripper(0.0)
    , quater_x(0.0)
    , quater_y(0.0)
    , quater_z(0.0)
    , quater_w(0.0)
    , chx(0.0)
    , chy(0.0)
    , chz(0.0)
    , vel_l(0.0)
    , vel_r(0.0)
    , height(0.0)
    , head_pit(0.0)
    , head_yaw(0.0)
    , temp_float_data()
    , temp_int_data()
    , mode1(0)
    , mode2(0)
    , time_count(0)  {
      temp_float_data.assign(0.0);

      temp_int_data.assign(0);
  }
  PosCmd_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , gripper(0.0)
    , quater_x(0.0)
    , quater_y(0.0)
    , quater_z(0.0)
    , quater_w(0.0)
    , chx(0.0)
    , chy(0.0)
    , chz(0.0)
    , vel_l(0.0)
    , vel_r(0.0)
    , height(0.0)
    , head_pit(0.0)
    , head_yaw(0.0)
    , temp_float_data()
    , temp_int_data()
    , mode1(0)
    , mode2(0)
    , time_count(0)  {
  (void)_alloc;
      temp_float_data.assign(0.0);

      temp_int_data.assign(0);
  }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _gripper_type;
  _gripper_type gripper;

   typedef double _quater_x_type;
  _quater_x_type quater_x;

   typedef double _quater_y_type;
  _quater_y_type quater_y;

   typedef double _quater_z_type;
  _quater_z_type quater_z;

   typedef double _quater_w_type;
  _quater_w_type quater_w;

   typedef double _chx_type;
  _chx_type chx;

   typedef double _chy_type;
  _chy_type chy;

   typedef double _chz_type;
  _chz_type chz;

   typedef double _vel_l_type;
  _vel_l_type vel_l;

   typedef double _vel_r_type;
  _vel_r_type vel_r;

   typedef double _height_type;
  _height_type height;

   typedef double _head_pit_type;
  _head_pit_type head_pit;

   typedef double _head_yaw_type;
  _head_yaw_type head_yaw;

   typedef boost::array<double, 6>  _temp_float_data_type;
  _temp_float_data_type temp_float_data;

   typedef boost::array<int32_t, 6>  _temp_int_data_type;
  _temp_int_data_type temp_int_data;

   typedef int32_t _mode1_type;
  _mode1_type mode1;

   typedef int32_t _mode2_type;
  _mode2_type mode2;

   typedef int32_t _time_count_type;
  _time_count_type time_count;





  typedef boost::shared_ptr< ::arx_msgs::PosCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arx_msgs::PosCmd_<ContainerAllocator> const> ConstPtr;

}; // struct PosCmd_

typedef ::arx_msgs::PosCmd_<std::allocator<void> > PosCmd;

typedef boost::shared_ptr< ::arx_msgs::PosCmd > PosCmdPtr;
typedef boost::shared_ptr< ::arx_msgs::PosCmd const> PosCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arx_msgs::PosCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arx_msgs::PosCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arx_msgs::PosCmd_<ContainerAllocator1> & lhs, const ::arx_msgs::PosCmd_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.gripper == rhs.gripper &&
    lhs.quater_x == rhs.quater_x &&
    lhs.quater_y == rhs.quater_y &&
    lhs.quater_z == rhs.quater_z &&
    lhs.quater_w == rhs.quater_w &&
    lhs.chx == rhs.chx &&
    lhs.chy == rhs.chy &&
    lhs.chz == rhs.chz &&
    lhs.vel_l == rhs.vel_l &&
    lhs.vel_r == rhs.vel_r &&
    lhs.height == rhs.height &&
    lhs.head_pit == rhs.head_pit &&
    lhs.head_yaw == rhs.head_yaw &&
    lhs.temp_float_data == rhs.temp_float_data &&
    lhs.temp_int_data == rhs.temp_int_data &&
    lhs.mode1 == rhs.mode1 &&
    lhs.mode2 == rhs.mode2 &&
    lhs.time_count == rhs.time_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arx_msgs::PosCmd_<ContainerAllocator1> & lhs, const ::arx_msgs::PosCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arx_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arx_msgs::PosCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arx_msgs::PosCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arx_msgs::PosCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arx_msgs::PosCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arx_msgs::PosCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arx_msgs::PosCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arx_msgs::PosCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8199bc204509c58732480f82fd3dfaed";
  }

  static const char* value(const ::arx_msgs::PosCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8199bc204509c587ULL;
  static const uint64_t static_value2 = 0x32480f82fd3dfaedULL;
};

template<class ContainerAllocator>
struct DataType< ::arx_msgs::PosCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arx_msgs/PosCmd";
  }

  static const char* value(const ::arx_msgs::PosCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arx_msgs::PosCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"float64 gripper\n"
"float64 quater_x\n"
"float64 quater_y\n"
"float64 quater_z\n"
"float64 quater_w\n"
"float64 chx\n"
"float64 chy\n"
"float64 chz\n"
"float64 vel_l\n"
"float64 vel_r\n"
"float64 height\n"
"float64 head_pit\n"
"float64 head_yaw\n"
"float64[6] temp_float_data\n"
"int32[6] temp_int_data\n"
"int32 mode1\n"
"int32 mode2\n"
"int32 time_count\n"
;
  }

  static const char* value(const ::arx_msgs::PosCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arx_msgs::PosCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.gripper);
      stream.next(m.quater_x);
      stream.next(m.quater_y);
      stream.next(m.quater_z);
      stream.next(m.quater_w);
      stream.next(m.chx);
      stream.next(m.chy);
      stream.next(m.chz);
      stream.next(m.vel_l);
      stream.next(m.vel_r);
      stream.next(m.height);
      stream.next(m.head_pit);
      stream.next(m.head_yaw);
      stream.next(m.temp_float_data);
      stream.next(m.temp_int_data);
      stream.next(m.mode1);
      stream.next(m.mode2);
      stream.next(m.time_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arx_msgs::PosCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arx_msgs::PosCmd_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "gripper: ";
    Printer<double>::stream(s, indent + "  ", v.gripper);
    s << indent << "quater_x: ";
    Printer<double>::stream(s, indent + "  ", v.quater_x);
    s << indent << "quater_y: ";
    Printer<double>::stream(s, indent + "  ", v.quater_y);
    s << indent << "quater_z: ";
    Printer<double>::stream(s, indent + "  ", v.quater_z);
    s << indent << "quater_w: ";
    Printer<double>::stream(s, indent + "  ", v.quater_w);
    s << indent << "chx: ";
    Printer<double>::stream(s, indent + "  ", v.chx);
    s << indent << "chy: ";
    Printer<double>::stream(s, indent + "  ", v.chy);
    s << indent << "chz: ";
    Printer<double>::stream(s, indent + "  ", v.chz);
    s << indent << "vel_l: ";
    Printer<double>::stream(s, indent + "  ", v.vel_l);
    s << indent << "vel_r: ";
    Printer<double>::stream(s, indent + "  ", v.vel_r);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "head_pit: ";
    Printer<double>::stream(s, indent + "  ", v.head_pit);
    s << indent << "head_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.head_yaw);
    s << indent << "temp_float_data[]" << std::endl;
    for (size_t i = 0; i < v.temp_float_data.size(); ++i)
    {
      s << indent << "  temp_float_data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.temp_float_data[i]);
    }
    s << indent << "temp_int_data[]" << std::endl;
    for (size_t i = 0; i < v.temp_int_data.size(); ++i)
    {
      s << indent << "  temp_int_data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.temp_int_data[i]);
    }
    s << indent << "mode1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode1);
    s << indent << "mode2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode2);
    s << indent << "time_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARX_MSGS_MESSAGE_POSCMD_H
